name: "Alert Manager"

on:
  workflow_dispatch:
  

jobs:
  Alert:
    name: Alert
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
        
    steps:
    
    - name: Issue creation
      uses: adrienpessu/alert-manager@main
      
