name: Java CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Run Spotless check
      run: mvn spotless:check
    - name: Run unit tests
      run: mvn test
    - name: Set up JDK 11 for Endor Scan
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Endor Labs Scan
      uses: endorlabs/github-action@v1.1.2
      with:
          namespace: 'david-learn'
          scan_summary_output_type: 'json'
          pr: false
          scan_secrets: true
          scan_dependencies: true
          enable_github_action_token: true
